nginx:
    build: nginx
    restart: always
    ports:
        - "80:80"
    links:
        - django
django:
    build: django
    restart: always
    command: gunicorn src.wsgi -w 2 -b 0.0.0.0:8000
    expose:
        - "8000"
    links:
        - mongo
    volumes:
        - ./django/src:/data/src
mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
        - ./data:/data/db
